spring:
  application:
    name: twitter-service

  datasource:
      url: jdbc:h2:mem:Tweet;DB_CLOSE_DELAY=-1
      platform: h2
      username: sa
      password:
      driverClassName: org.h2.Driver
  jpa:
     database-platform: org.hibernate.dialect.H2Dialect
     hibernate:
       ddl-auto: update
       cache:
         use_second_level_cache: true
         use_query_cache: true
         region:
          factory_class : org.hibernate.cache.ehcache.EhCacheRegionFactory

server:
  port: 2223

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
     leaseRenewalIntervalInSeconds: 10
     metadataMap:
      instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${server.port}}}

endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic
