spring:
    application:
      name: zuul-service

zuul:
  ignoredServices: "*"
  routes:
    configurationapi:
      path: "/api/configuration/**"
      serviceId: criteria-service
      stripPrefix: true
    api:
      path: "/api/**"
      serviceId: twitter-service
      stripPrefix: true

server:
    port: 8080

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 3
    leaseExpirationDurationInSeconds: 2
    metadataMap:
      instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${random.value}}}
  client:
    serviceUrl:
      defaultZone: ${vcap.services.${PREFIX:}eureka.credentials.uri:http://user:password@localhost:8761}/eureka/




